manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: spindlemax
      url base: https://github.com/spindlemax/zmk.git
  projects:
    - name: zmk
      remote: spindlemax
      revision: main
      import: app/west.yml
  self:
    path: config
